### ISSUE TITLE
Intuition on VRAM requirements for various models + quantization recipes 

### ISSUE THREAD

**Issue by selalipop** [vllm-project/llm-compressor#1007]
**What is the URL, file, or UI containing proposed doc change**
README.md, or an addendum

**What is the current content or situation in question**
The naive understanding would be that llm-compressor requires roughly the VRAM of the unquantized model + some overhead, and that overhead is affected by the exact recipe and arguments (speed/memory tradeoff)

**What is the proposed change**
It could be very helpful to give a few examples, or a rough dimensional estimate of how much VRAM is needed relative to various base models and for various recipes

**Additional context**
This helps with ensuring users aren't over/under provisioning for the task. In my case I jumped to 2xH200 for a 123B model to avoid a run possibly failing mid run. Happy to seed this with my findings once the run is completed

**Comment by selalipop** [comment]
Actually, found this under a secondary readme:

> Note that running non-sequential GPTQ requires significant additional memory beyond the model size. As a rough rule of thumb, running GPTQModifier non-sequentially will take up 3x the model size for a 16-bit model and 2x the model size for a 32-bit model (these estimates include the memory required to store the model itself in GPU).

**Comment by kylesayrs** [comment]
Hi @selalipop! This is indeed a good intuition. You can also check out some examples of [quantizing large models using accelerate](https://github.com/vllm-project/llm-compressor/blob/main/examples/big_models_with_accelerate/mult_gpus_int8_device_map.py#L15C14-L15C42) and the `calculate_offload_device_map` function.

Keep in mind, these requirements are likely to change slightly in the next release as more options for running forward calibration through models are introduced.

Please feel free to reopen if you have any specific questions about specific models or algorithms!
