### ISSUE TITLE
[Bug]: Index Error tuple out of range

### ISSUE THREAD

**Issue by SeanIsYoung** [vllm-project/llm-compressor#106]
**Describe the bug**
I'm trying to apply "W4A16" quantisation to the qwen2-7B model. In particular "cognitivecomputations/dolphin-2.9.2-qwen2-7b" though I've tried with other qwen2 models and had the same problem.

Using the code:
```python
device_map = calculate_offload_device_map(
    model_path,
    reserve_for_hessians=True,
    num_gpus=1,
    trust_remote_code=True,
)

model = SparseAutoModelForCausalLM.from_pretrained(
    model_path,
    device_map=device_map,
    torch_dtype="auto",
    trust_remote_code=True,
)
tokenizer = AutoTokenizer.from_pretrained(model_path)
ds = dataset_construction.get_datasets(
    dataset_construction.DATASETS,
    tokenizer,
    sample_size=sample_size,
    min_seq_len=min_seq_len,
    max_seq_len=max_seq_len,
)

recipe = GPTQModifier(targets="Linear", scheme="W4A16", ignore=["lm_head"], sequential_update=True)

oneshot(
    model=model,
    tokenizer=tokenizer,
    recipe=recipe,
    dataset=ds,
    max_seq_length=max_seq_len if max_seq_len is not None else dataset_construction.MAX_SEQUENCE_LENGTH,
    num_calibration_samples=ds.num_rows,
    save_compressed=True,
    output_dir=quantized_models_path
)
```

I get the following error:
```bash
Traceback (most recent call last):
  File "/home/youngs/ag-rag/src/experiments/llms/llm-compressor.py", line 145, in <module>
    quantize(args.model_id, models_dir, gptq_dir, "W4A16",
  File "/home/youngs/ag-rag/src/experiments/llms/llm-compressor.py", line 39, in quantize
    device_map = calculate_offload_device_map(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youngs/llm-compressor/src/llmcompressor/transformers/compression/helpers.py", line 222, in calculate_offload_device_map
    reserved_memory = hessian_memory_requirements(dummy_model)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/youngs/llm-compressor/src/llmcompressor/transformers/compression/helpers.py", line 116, in hessian_memory_requirements
    column_size = param.shape[1]
                  ~~~~~~~~~~~^^^
IndexError: tuple index out of range
```

I don't know enough about how this works to fix it for certain. But amending the line 116 in the helpers file to the following works.
```python
column_size = param.shape[1] if len(param.shape) >= 2 else 0
```

Making this change allows it to run to completion and the model appears to be fully functional *(I can run it and get reasonable results back. Haven't played with evaluations yet.)*.

It does however produce the following warning. I haven't seen this one before and so I'm not sure if this is a consequence of what I changed or just this model in particular:

```bash
/home/youngs/anaconda3/envs/llmcompressor/lib/python3.11/site-packages/accelerate/utils/modeling.py:1405: UserWarning: Current model requires 671091200 bytes of buffer for offloaded layers, which seems does not fit any GPU's remaining memory. If you are experiencing a OOM later, please consider using offload_buffers=True.
  warnings.warn(
```

**Expected behavior**
To be able to successfully quantise the model without any errors.

**Environment**
Include all relevant environment information:
1. OS: WSL - Ubuntu 22.04.4 LTS
2. Python version: 3.11.9
3. LLM Compressor version or commit hash: 9ef530c9
4. ML framework version(s): transformers==4.44.0, torch==2.4.0
5. Other Python package versions [e.g. vLLM, compressed-tensors, numpy, ONNX]: vllm==0.5.4, numpy==1.26.4, compressed-tensors==0.5.0, onnx==1.16.2
6. Other relevant environment information [e.g. hardware, CUDA version]: CUDA 12.1

**Comment by robertgshaw2-neuralmagic** [comment]
Thanks @SeanIsYoung this is a bug in our accelerate related code. We will take a look and try to resolve

For now, I can suggest some workarounds:
- what size GPU are you running this on?

**Comment by SeanIsYoung** [comment]
>     * what size GPU are you running this on?

Sorry for the delayed response @robertgshaw2-neuralmagic. I'm using an **RTX 4080 Super with 16GB** of memory.

And to reiterate with regards the user warning, it runs to completion with the above settings and according to task manager it is still making use of the gpu.

**Comment by okwinds** [comment]
the same problems

**Comment by kylesayrs** [comment]
Fixed by https://github.com/vllm-project/llm-compressor/pull/836
