### ISSUE TITLE
convert model to FP8 error

### ISSUE THREAD

**Issue by kuangdao** [vllm-project/llm-compressor#110]
**Describe the bug**

**Expected behavior**

**Environment**
Include all relevant environment information:
1. OS [Ubuntu 20.04]:
2. Python version [3.10.12]:
3. LLM Compressor version or commit hash [0.1.0]:
4. ML framework version(s) [2.4.0]:
5. Other Python package versions [e.g. vLLM, compressed-tensors, numpy, ONNX]:
6. Other relevant environment information [e.g. hardware, CUDA version]:

**To Reproduce**

```

from llmcompressor.transformers import SparseAutoModelForCausalLM
from transformers import AutoTokenizer

MODEL_ID = "/data/models/deepseek-coder-6.7b-base/"

model = SparseAutoModelForCausalLM.from_pretrained(
  MODEL_ID, device_map="auto", torch_dtype="auto")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)


from llmcompressor.transformers import oneshot
from llmcompressor.modifiers.quantization import QuantizationModifier

# Configure the simple PTQ quantization
recipe = QuantizationModifier(
  targets="Linear", scheme="FP8_DYNAMIC", ignore=["lm_head"])

# Apply the quantization algorithm.
oneshot(model=model, recipe=recipe)

# Save the model.
SAVE_DIR = MODEL_ID.split("/")[1] + "-FP8-Dynamic"
model.save_pretrained(SAVE_DIR)
tokenizer.save_pretrained(SAVE_DIR)

```

**Errors**

<img width="1416" alt="截屏2024-08-26 10 49 07" src="https://github.com/user-attachments/assets/c814bf0b-3685-433c-958a-04f21e255f15">

**Additional context**

**Comment by robertgshaw2-neuralmagic** [comment]
Can you share:
- torch version
- are you running on cpu or gpu


It looks like max for fp8 is not supported on your torch version

**Comment by markurtz** [comment]
Closing this out due to lack of activity. Feel free to open it up if you are still hitting the issue!
