### ISSUE TITLE
[Performance]: SmoothQuant quantization is too slow

### ISSUE THREAD

**Issue by zxy1119** [vllm-project/llm-compressor#112]
### Proposal to improve performance

I am using SmoothQuant to quantize Llama2-7b, but each sample takes 1 hour. Is this speed normal, and are there any ways to improve it?
![image](https://github.com/user-attachments/assets/a11b9d1b-63b5-4c9c-8d41-25f647096d50)

### Your current environment (if you think it is necessary)

```text
The output of `python collect_env.py`
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by robertgshaw2-neuralmagic** [comment]
> ### Proposal to improve performance
> I am using SmoothQuant to quantize Llama2-7b, but each sample takes 1 hour. Is this speed normal, and are there any ways to improve it? ![image](https://private-user-images.githubusercontent.com/57778474/361323418-a11b9d1b-63b5-4c9c-8d41-25f647096d50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjE4NzgsIm5iZiI6MTcyNDc2MTU3OCwicGF0aCI6Ii81Nzc3ODQ3NC8zNjEzMjM0MTgtYTExYjlkMWItNjNiNS00YzljLThkNDEtMjVmNjQ3MDk2ZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEyMjYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MGIwMzdlZjQyMjNkZGJhYzhmZGVlZmRlZDQ0Zjg0MjcxMmNiMWFmZGRkZjQ5YjRjYjZhZjA1Y2U5ZjlkNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kwEyJF8QfxYOamIahe0YW_zitDwp96BvjZnEJkiWSJ8)
> 
> ### Report of performance regression
> _No response_
> 
> ### Misc discussion on performance
> _No response_
> 
> ### Your current environment (if you think it is necessary)
> ```
> The output of `python collect_env.py`
> ```
> 
> ### Before submitting a new issue...
> * [x]  Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

Can you share some more info about your environment? Are you running on CPU?

**Comment by markurtz** [comment]
I'm closing this out due to a lack of activity. If you're still having this issue, please feel free to reopen it!

**Comment by markurtz** [comment]
I'm closing this out due to a lack of activity. If you're still having this issue, please feel free to reopen it!
