### ISSUE TITLE
Do we have a roadmap?

### ISSUE THREAD

**Issue by CharlesRiggins** [vllm-project/llm-compressor#128]
We've found the llm-compressor to be a powerful quantization tool that integrates seamlessly with vLLM. We are considering using llm-compressor to replace tools like AutoAWQ, AutoGPTQ, and others in our production.

We would love to learn more about the future direction of llm-compressor. Could you please share if there is a roadmap available, similar to what vLLM has (as seen [here](https://github.com/vllm-project/vllm/issues/5805))?

Thank you for your excellent work.

**Comment by robertgshaw2-neuralmagic** [comment]
Current roadmap is here:
- https://github.com/vllm-project/llm-compressor/issues/30

Any requests would be great!

**Comment by CharlesRiggins** [comment]
Great. Thank you for replying.
