### ISSUE TITLE
[Usage] Where to set the tokenizer in the sparse example?

### ISSUE THREAD

**Issue by CharlesRiggins** [vllm-project/llm-compressor#129]
[quantization_24_sparse_w4a16](https://github.com/vllm-project/llm-compressor/tree/main/examples/quantization_24_sparse_w4a16/llama7b_sparse_w4a16.py)

I noticed that in the llama7b_sparse_w4a16 example, there doesn’t seem to be an option to specify a tokenizer. I’m curious if the example is using a LLaMA tokenizer by default. If so, this might be incorrect when other models are used.

**Comment by markurtz** [comment]
Good question; you can pass in the tokenizer with the tokenizer arg key. Otherwise it will default to loading the tokenizer used by the model.

**Comment by markurtz** [comment]
Good question; you can pass in the tokenizer with the tokenizer arg key. Otherwise it will default to loading the tokenizer used by the model.
