### ISSUE TITLE
AttributeError: 'QuantizationArgs' object has no attribute 'actorder' for in4 quantization example

### ISSUE THREAD

**Issue by Justin-Uniphore** [vllm-project/llm-compressor#130]
Hi, I am running the example at https://github.com/vllm-project/llm-compressor/blob/main/examples/quantization_w4a16/llama3_example.py

when running the example script, the titled error of `AttributeError: 'QuantizationArgs' object has no attribute 'actorder'` is happening. I am guessing it's some dependency issues, and create a brand new virtual environment, installed the dependency in this new virtual environment and run it again, and still observe the same issue. What could be the potential fix to this?

**Comment by robertgshaw2-neuralmagic** [comment]
@Justin-Uniphore are you installing from source?

Can you run the official release? `pip install llmcompressor`

**Comment by Justin-Uniphore** [comment]
Hi, when I first write the issue, I am following the https://github.com/vllm-project/llm-compressor/tree/main/examples/quantization_w4a16 so I am doing `pip install -e .` I just ran `pip install llmcompressor` and still have the same bug.

**Comment by Justin-Uniphore** [comment]
Update: after I uninstall the llmcompressor with `pip uninstall llmcompressor` and install it again with `pip install llmcompressor`, the bug disappeared. Might be a good idea to update the document then. Thanks for the great work.

**Comment by robertgshaw2-neuralmagic** [comment]
Sorry about that - we have a new release coming up and need to update the example.

**Comment by robertgshaw2-neuralmagic** [comment]
@kylesayrs FYI

**Comment by kylesayrs** [comment]
Hi @Justin-Uniphore! This bug is part of our added support for activation ordering, as specified in `QuantizationArgs`. Right now you're running with our latest release, but if you would like to run with our `main` branch, you can install the latest compressed-tensors branch like so
```
git clone https://github.com/neuralmagic/compressed-tensors
cd compressed-tensors
python3 -m pip install -e .
cd llm-compressor
python3 -m pip install -e .
```
