### ISSUE TITLE
GPTQ example README bug

### ISSUE THREAD

**Issue by CharlesRiggins** [vllm-project/llm-compressor#136]
**What is the URL, file, or UI containing proposed doc change**
https://github.com/vllm-project/llm-compressor/blob/main/examples/quantization_w4a16/README.md

**What is the current content or situation in question**
```
from llmcompressor.transformers import oneshot
from llmcompressor.modifiers.quantization import QuantizationModifier

# Configure the quantization algorithm to run.
recipe = GPTQModifier(targets="Linear", scheme="W4A16", ignore=["lm_head"])
```

**What is the proposed change**
```
from llmcompressor.transformers import oneshot
from llmcompressor.modifiers.quantization import GPTQModifier

# Configure the quantization algorithm to run.
recipe = GPTQModifier(targets="Linear", scheme="W4A16", ignore=["lm_head"])
```

**Additional context**

GPTQModifier should be imported, not QuantizationModifier.

**Comment by robertgshaw2-neuralmagic** [comment]
Thanks - fixed by https://github.com/vllm-project/llm-compressor/pull/139
