### ISSUE TITLE
When can we support w8a8 fp8 quantization and sparse2:4 llm compress and adapt it on vllm?

### ISSUE THREAD

**Issue by leoyuppieqnew** [vllm-project/llm-compressor#148]

**Comment by robertgshaw2-neuralmagic** [comment]
This is something we are actively working on supporting end-to-end. 

In vllm, we currently support 2:4 sparsity with w4A16 and w8a16. We need to add inference kernels to support w8a8 fp8 with sparse 2:4. We are collaborating the cutlass teams on this.

**Comment by chaldipok3** [comment]
v

**Comment by bebeynen** [comment]
cx

**Comment by markurtz** [comment]
A quick update: We hope to have end-to-end support and a model launch within the next few weeks!

**Comment by robertgshaw2-neuralmagic** [comment]
Closing since we will have updates on 2:4 in next release.
