### ISSUE TITLE
using smoothquant and gptq example, but model size has increased

### ISSUE THREAD

**Issue by designeryuan** [vllm-project/llm-compressor#162]
**Describe the bug**
i using the smoothquant and gptq to quantify Qwen2-0.5B-Instruct, but the model size has increased， which from 0.94G to 1.85G

**Expected behavior**

**Environment**
Include all relevant environment information:
1. OS Ubuntu 20.04
2. Python version 3.10:
3. LLM Compressor version 0.1.0

**To Reproduce**

```
from llmcompressor.transformers import oneshot
from llmcompressor.modifiers.quantization import GPTQModifier
from llmcompressor.modifiers.smoothquant import SmoothQuantModifier
from llmcompressor.transformers import SparseAutoModelForCausalLM
from transformers import AutoTokenizer
logger.info(f"begin to smooth_quant quantization")

MODEL_ID = "my model path"
SAVE_DIR = "my save path"
model = SparseAutoModelForCausalLM.from_pretrained(
    MODEL_ID, device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
# load calib_file
ds = load_llmcompressor_json("my calib file path", tokenizer)

# Configure the quantization algorithms
recipe = [
    SmoothQuantModifier(smoothing_strength=0.8),
    GPTQModifier(scheme="W8A8", targets="Linear", ignore=["lm_head"]),
]

# Apply quantization
oneshot(
    model=MODEL_ID,
    dataset=ds,
    recipe=recipe
)

# Save the compressed model
logger.info(f"save model to {SAVE_DIR}")
model.save_pretrained(SAVE_DIR, save_compressed=True)
tokenizer.save_pretrained(SAVE_DIR)
````

**Errors**
origin model size: 0.94 GB
quant model size: 1.85 GB

**Comment by robertgshaw2-neuralmagic** [comment]
Are you measuring the model size on disk or in transformers?

Right now `SparseAutoModel` will not reduce memory consumption when running the quantized model. `v0.2.0` of `llm-compressor` will enable this though. The target of these quantized models is running in vllm. You will see performance acceleration and memory reduction when deploying the model in vllm.

**Comment by robertgshaw2-neuralmagic** [comment]
Closing for now.
