### ISSUE TITLE
DeepseekV2-w8a8 weight needed in HF

### ISSUE THREAD

**Issue by Eviannn** [vllm-project/llm-compressor#175]
Hi,

I try to quant DeepseekV2 full model in 8*A800 but it took too much time, and when someone else use gpus at the same time, oom would occur, so I hope I could download DeepseekV2-w8a8 weight from HF, like: https://huggingface.co/nm-testing/DeepSeek-Coder-V2-Lite-Instruct-W8A8/tree/main .

Besides, are you going to adapt DeepseekV2-w8a8 to vllm? I think now vllm does not support compressed-tensor-w8a8.

**Comment by dengzheng-cloud** [comment]
maybe not someone use GPUS cause your OOM, i m using llmcomrepssor to quantize deepseek v2.5 with 8*A100 and watching nvidia-smi, while still get OOM, this confused me a lot.

**Comment by markurtz** [comment]
Hi @Eviannn, we have models available now for Deepseek V2. Check them out here:
- https://huggingface.co/neuralmagic/DeepSeek-Coder-V2-Lite-Instruct-FP8
-  https://huggingface.co/neuralmagic/DeepSeek-Coder-V2-Instruct-FP8
