### ISSUE TITLE
[ UX ] Skip Running First Cycle Through Dataset for Weight-Only Quantization

### ISSUE THREAD

**Issue by robertgshaw2-neuralmagic** [vllm-project/llm-compressor#29]
Currently, we run one cycle through the dataset for `QuantizationModifier` for weight-only quantization.

This ~doubles the runtime of a GPTQ  run

**Comment by Satrat** [comment]
This was fixed as part of https://github.com/vllm-project/llm-compressor/pull/34, closing this issue!
