### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by Lin-K76** [vllm-project/llm-compressor#43]
**Describe the bug**

When trying to quantize the StarCoder2 models, I run into a index error due to estimates of the quantization. Specifically, there are certain parameters that are not two dimensional that are thought to be.

**Expected behavior**

Successful quantization of StarCoder2 models.

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: Ubuntu 22.04.4
2. Python version [e.g. 3.7]: 3.11.9
3. LLM Compressor version or commit hash [e.g. 0.1.0, `f7245c8`]: 2c0714d0d4ebf49676f3fb17116b6aac955dc8cf
4. ML framework version(s) [e.g. torch 1.7.1]: torch 2.3.1, transformers 4.44.0.dev0
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]:
6. Other relevant environment information [e.g. hardware, CUDA version]: CUDA 12.5

**To Reproduce**
Exact steps to reproduce the behavior:

Following the example in https://github.com/vllm-project/llm-compressor/blob/sa/big_model_support/examples/big_model_offloading/big_model_w8a8_calibrate.py, changing the model name to "bigcode/starcoder2-3b" causes the error.

**Errors**
If applicable, add a full print-out of any errors or exceptions that are raised or include screenshots to help explain your problem.

**Additional context**

Can fix with changing the erroneous line to max_quant_shape = param.shape[0] .

**Comment by robertgshaw2-neuralmagic** [comment]
FYI - @Satrat 

I can repo this issue with:

```
import torch
from transformers import AutoTokenizer

from llmcompressor.transformers import SparseAutoModelForCausalLM, oneshot
from llmcompressor.transformers.compression.helpers import (  # noqa
    calculate_offload_device_map,
    custom_offload_device_map,
)

# define a llmcompressor recipe for FP8 quantization
# this recipe requires no calibration data since inputs are dynamically quantized
recipe = """
quant_stage:
    quant_modifiers:
        QuantizationModifier:
            ignore: ["lm_head"]
            config_groups:
                group_0:
                    weights:
                        num_bits: 8
                        type: float
                        strategy: channel
                        dynamic: false
                        symmetric: true
                    input_activations:
                        num_bits: 8
                        type: float
                        strategy: token
                        dynamic: true
                        symmetric: true
                    targets: ["Linear"]
"""

model_stub = "bigcode/starcoder2-3b"

# determine which layers to offload to cpu based on available resources
device_map = calculate_offload_device_map(
    model_stub, reserve_for_hessians=False, num_gpus=1, torch_dtype=torch.float16
)

# alternatively, specify the maximum memory to allocate per GPU directly
# device_map = custom_offload_device_map(
#    model_stub, max_memory_per_gpu="10GB", num_gpus=2, torch_dtype=torch.float16
# )

model = SparseAutoModelForCausalLM.from_pretrained(
    model_stub, torch_dtype=torch.float16, device_map=device_map
)

output_dir = "./output_fp8"


oneshot(
    model=model,
    recipe=recipe,
    output_dir=output_dir,
    save_compressed=True,
    tokenizer=AutoTokenizer.from_pretrained(model_stub),
)

```

**Comment by robertgshaw2-neuralmagic** [comment]
resolved by https://github.com/vllm-project/llm-compressor/pull/71
