### ISSUE TITLE
Reproduce "Quick Tour"

### ISSUE THREAD

**Issue by caojinpei** [vllm-project/llm-compressor#46]
**Describe the bug**
After I downloaded TinyLlama-1.1B-Chat-v1.0 model and open_platypus dataset from huggingface to local server, then I replace the model/dataset path presented in the "Quick Tour" , but it failed.

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]:
2. Python version 3.8.19
3. llmcompressor==1.8.0.dev0
4. torch==2.4.0+cu121

**To Reproduce**
Exact steps to reproduce the behavior:

**Errors**
Below is error logs:

KeyError: "Unable to find None registered under type <class 'llmcompressor.transformers.finetune.data.base.TextGenerationDataset'>.\nRegistered values for <class 'llmcompressor.transformers.finetune.data.base.TextGenerationDataset'>: ['c4', 'cnn-dailymail', 'custom', 'evolcodealpaca', 'gsm8k', 'open-platypus', 'ptb', 'ultrachat-200k', 'wikitext']\nRegistered aliases for <class 'llmcompressor.transformers.finetune.data.base.TextGenerationDataset'>: ['json', 'csv']"

**Additional context**
I guess the errors show that only ['c4', 'cnn-dailymail', 'custom', 'evolcodealpaca', 'gsm8k', 'open-platypus', 'ptb', 'ultrachat-200k', 'wikitext'] can be supported to quantize model in the llm-compressor, am I right?

Can you help me check this issue? And now I want to quantize LLaVA model using llm-compressor, how can I build the collabration dataset? If possible, could you provide me with the sample codes? Thanks a lot.

**Comment by Satrat** [comment]
Hi @caojinpei, llm-compressor has a few datasets built in that you can reference by name for calibration, but it is also possible to supply your own calibration data. This is done by passing a tokenized `Dataset` object to the dataset argument in the oneshot call.

You can find an example of custom calibration data here: https://github.com/vllm-project/llm-compressor/blob/main/examples/quantization_w8a8_int8/llama3_example.py
