### ISSUE TITLE
~!Curling LIVE!! PointsBet Invitational 2024 Invitational LIVE STREAMS Curling ON TV CHANNEL in 25 September 2024

### ISSUE THREAD

**Issue by lapizvish** [vllm-project/llm-compressor#661]
The 2024 PointsBet Invitational curling tournament will be held from September 25 to 29 at the Markin MacPhail Centre at Canada Olympic Park in Calgary, Alberta. The event will feature thirty-two Canadian teams and will be the first major event of the 2024–25 season. It will be played in a single-elimination tournament with the winning team on both the men's and women's sides receiving $50,000 each.

[🅻🅸🆅🅴 CLICK HERE TO WATCH LIVE ONLINE  ](https://special.procast.live/?refd_by=clicktvt)

[🆆🅰🆃🅲🅷 CLICK HERE TO LIVE STREAM](https://special.procast.live/?refd_by=clicktvt)

The 2024 PointsBet Invitational, the first major curling event of the 2024–25 season, will take place from September 25 to 29, 2024 at the Markin MacPhail Centre in Canada Olympic Park, Calgary. The tournament will bring together thirty-two of Canada’s top teams, competing in a high-stakes single-elimination format for a share of the $100,000 prize pool.

Event Highlights

Dates: September 25–29, 2024
Location: Markin MacPhail Centre, Canada Olympic Park, Calgary, Alberta
Format: Single-elimination tournament
Prize Money: $50,000 each for the winning men’s and women’s teams
The Competition

The PointsBet Invitational is designed to create an exciting, fast-paced competition, as every game will be a must-win for teams hoping to advance. With thirty-two teams in total—split evenly between men’s and women’s competitions—the stakes are high from the very first draw.

PointsBet Invitational 2023: Dates, times, schedule and how to watch the kickoff Canadian curling event

The weather is cooling off, but the curling rinks are just heating up.  

Curling is finally back, as the 2023 PointsBet Invitational kicks off the 2023-24 season in Canada. The competition, which made its debut last year, features 16 of the best men's teams and 16 of the best women's rinks from the country. 

The format of the tournament differs from a majority of the others. Instead of playing in a round-robin format with a knockout stage, the PointsBet Invitational is single elimination, as the field will be cut down from 16 to eight to four to two and then finally, a champion will be crowned.

The defending champions from the 2022 event are both Manitoba rinks, as Reid Carruthers won on the men's side, and Jennifer Jones was crowned the champion for the women. 

Here is everything you need to know about the 2023 PointsBet Invitational. 

2023 PointsBet Invitational bracket
Both the men's and women's competitions involve 16 of the top-ranked teams in the country. 

The tournament is played in a single-elimination style. It starts with 16 teams playing in the Sweep 16 before the winners advance to the Elite 8, then the Final 4 and lastly, the final. 

Men's bracket
Sweep 16

No. 1 Gushue vs. No. 16 Balsdon
No. 8 Epping vs. No. 9 Wiebe

No. 5 Carruthers vs. No. 12 Tao
No. 4 Koe vs. No. 13 Kleiter

No. 6 Sturmay vs. No. 11 Howard
No. 3 Dunstone vs. No. 14 Mooibroek

No. 7 Sluchinski vs. No. 10 McEwen
No. 2 Bottcher vs. No. 15 Dobson

Elite 8

No. 1 Gushue vs. No. 9 Wiebe
No. 5 Carruthers vs. No. 13 Kleiter

No. 2 Bottcher vs. No. 10 McEwen
No. 3 Dunstone vs. No. 6 Sturmay

Final 4

No. 1 Gushue vs. No. 5 Carruthers
No. 3 Dunstone vs. No. 10 McEwen  

Final

No. 3 Dunstone vs. No. 5 Carruthers

Women's bracket
Sweep 16

No. 1 Einarson vs. No. 16 Zimmerman
No. 8 Skrlik vs. No. 9 Inglis

No. 5 Grandy vs. No. 12 Duncan
No. 4 Lawes vs. No. 13 Marks

No. 6 Black vs. No. 11 Martin
No. 3 Jones vs. No. 14 Plett

No. 7 Ladouceur vs. No. 10 Gray-Withers
No. 2 Homan vs. No. 15 Park

Elite 8

No. 1 Einarson vs. No. 8 Skrlik
No. 4 Lawes vs. No. 5 Grandy

No. 2 Homan vs. No. 7 Ladouceur
No. 3 Jones vs. No. 6 Black

Final 4

No. 2 Homan vs. No. 6 Black   
No. 1 Einarson vs. No. 4 Lawes  

Final

No. 1 Einarson vs. No. 2 Homan

2023 PointsBet Invitational schedule, results
Wednesday, Sept. 27
Women's

Matchup	Time (ET)
No. 4 Lawes 11, No. 13 Marks 5	FINAL
No. 5 Grandy 6, No. 12 Duncan 5	FINAL
No. 1 Einarson 15, No. 16 Zimmerman 3    	FINAL
No. 8 Skrlik 7, No. 9 Inglis 6	FINAL
Men's

Matchup	Time (ET)
No. 13 Kleiter 10, No. 4 Koe 6	FINAL
No. 5 Carruthers 10, No. 12 Tao 3              	FINAL
No. 1 Gushue 9 No. 16 Balsdon 4  	FINAL
No. 9 Wiebe 8, No. 8 Epping 5	FINAL
Thursday, Sept. 28
Women's

Matchup	Time (ET)
No. 6 Black 8, No. 11 Martin 7	FINAL
No. 3 Jones 10, No. 14 Plett 6	FINAL
No. 2 Homan 11, No. 15 Park 1	FINAL
No. 7 Ladouceur 8, No. 10 Gray-Withers 6   	FINAL
Men's

Matchup	Time (ET)
No. 6 Sturmay 8 No. 11 Howard, 4	FINAL
No. 3 Dunstone 10, No. 14 Mooibroek 5	FINAL
No. 2 Bottcher 7, No. 15 Dobson 1            	FINAL
No. 10 McEwen 11, No. 7 Sluchinski 5	FINAL
Friday, Sept. 29
Women's

Matchup	Time (ET)
No. 2 Homan 10, No. 7 Ladouceur 6	FINAL
No. 1 Einarson 10, No. 8 Skrlik 6               	FINAL
No. 6 Black 9, No. 3 Jones 6	FINAL
No. 4 Lawes 8, No. 5 Grandy 3	FINAL
Men's

Matchup	Time (ET)
No. 10 McEwen 9, No. 2 Bottcher 5	FINAL
No. 1 Gushue 8, No. 9 Wiebe 4	FINAL
No. 3 Dunstone 8, No. 6 Sturmay 5	FINAL
No. 5 Carruthers 9, No. 13 Kleiter 8      	FINAL
Saturday, Sept. 30
Women's

Matchup	Time (ET)
No. 2 Homan 10, No. 6 Black 5          	FINAL
No. 1 Einarson 8 No. 4 Lawes, 3    	FINAL
Men's

Matchup	Time (ET)
No. 3 Dunstone 6, No. 10 McEwen 5  	FINAL
No. 5 Carruthers 6, No. 1 Gushue 5	FINAL
Sunday, Oct. 1
Women's

Matchup	Time (ET)
No. 2 Homan 9, No. 1 Einarson 7       	FINAL
Men's 

Matchup	Time (ET)
No. 5 Carruthers 9, No. 3 Dunstone 8 	FINAL
When is the 2023 PointsBet Invitational?
Dates: Sept. 27 - Oct. 1
This tournament begins on Wednesday, Sept. 27, with the finals set to take place on Sunday, Oct. 1. 

The Sweep 16 will run for the first two days, followed by the Elite 8 on Friday, Sept. 28, the Final 4 on Saturday, Sept. 29 and the finals on Sunday, Sept. 30. 

What channel is the 2023 PointsBet Invitational?
TV Channel: TSN
Live stream: TSN.ca, TSN app
The 2023 PointsBet Invitational will be on TSN for the entire tournament. 

Fans can either watch live on TSN, or stream the competition on TSN.ca or on the TSN app. 

2023 PointsBet Invitational TV schedule
Date	Time (ET)	Round	TV Channel
Wednesday, Sept. 27	2 p.m.	Sweep 16	TSN 1/4
Wednesday, Sept. 27	7 p.m.	Sweep 16	TSN 4
Thursday, Sept. 28	2 p.m.	Sweep 16	TSN 1/4
Thursday, Sept. 28	7 p.m.	Sweep 16	TSN 1/4
Friday, Sept. 29	11:30 a.m.	Elite 8	TSN 1/4
Friday, Sept. 29	4:30 p.m.	Elite 8	TSN 1
Saturday, Sept. 30	Noon	Final 4	TSN 3/5
Saturday, Sept. 30	5 p.m.	Final 4	TSN 3
Sunday, Oct. 1	Noon	Women's Final	TSN 4
Sunday, Oct. 1	5 p.m.	Men's Final	TSN 4
Where is the 2023 PointsBet Invitational taking place?
City: Oakville, Ont.
Venue: Sixteen Mile Sports Complex
This year's tournament is hosted at Sixteen Mile Sports Complex in Oakville, Ontario.

Last year, the inaugural PointsBet Invitational was held in Fredericton, N.B., so the event will change location each year. 

2023 PointsBet Invitational prize money
In total there is a $350,000 purse up for grabs at the PointsBet Invitational. 

Teams will earn more money for each win, eventually resulting in the champions on both the men's and women's sides receiving $50,000 each, in addition to the previous money earned in the earlier rounds. 

Here is how the prize money breaks down for this tournament:

First Round win: $3,000
Quarterfinal win: $6,000
Semifinal win: $12,000
Champion: $50,000

[🅻🅸🆅🅴 CLICK HERE TO WATCH LIVE ONLINE  ](https://special.procast.live/?refd_by=clicktvt)

[🆆🅰🆃🅲🅷 CLICK HERE TO LIVE STREAM](https://special.procast.live/?refd_by=clicktvt)

**Comment by kristinsulap** [comment]
PointsBet Invitational 2024 Invitational

**Comment by itonirban** [comment]
PointsBet Invitational 2024
