### ISSUE TITLE
++HERE’S!!* WAY TO WATCH PointsBet Invitational 2024 LIVE STREAMS ON TV CHANNEL 25 SEP 2024

### ISSUE THREAD

**Issue by lapizvish** [vllm-project/llm-compressor#663]
Sudden-death drama will be the storyline over five days of high-calibre curling when the 2024 PointsBet InvitationalOpens in a new window gets underway Wednesday at the WinSport Event Centre in Calgary. Sixteen men’s and sixteen women’s teams are entered in the third annual PointsBet Invitational, all looking to get their 2024-25 campaigns kicked off in style, not to mention grab a big chunk of a prize purse in excess of $350,000.

[🅻🅸🆅🅴 CLICK HERE TO WATCH LIVE ONLINE](https://special.procast.live/?refd_by=clicktvt)

[🆆🅰🆃🅲🅷 CLICK HERE TO LIVE STREAM](https://special.procast.live/?refd_by=clicktvt)

Winnipeg’s Team Kaitlyn Lawes are set to begin their third season as a foursome and will take on Victoria’s Taylor Reese-Hansen in the opening round of the Sweep 16.

Team Lawes have lost in the semifinals in each of the previous two PointsBet Invitational events while Team Reese-Hansen will make their debut after winning the U25 NextGen Classic earlier this season.

As a Scotties Tournament of Hearts rookie, 25-year-old Selena Sturmay led her young Alberta foursome to a playoff appearance in front of a hometown crowd at Calgary’s WinSport arena last February.

Sturmay and company return to the location of their memorable run last winter, looking for some more magic at the PointsBet Invitational.

They’ll take on Saskatoon’s Team Ashley Thevenot, who also competed at the Calgary Scotties, in the Sweep 16.

Team Thevenot were skipped by Skylar Ackerman at last year's Scotties and almost made the playoffs with a 4-4 round robin record. Ackerman announced at the end of the season she was leaving competitive curling. Thevenot, who was the vice, took over skip duties for 2024-25 and added Brittany Tran to the team.

As a 13th seed, Sturmay upset a rink led by Chelsea Carey at the inaugural Sweep 16 in 2022 before losing to Jennifer Jones in the Elite 8.

Thevenot will make her PointsBet Invitational debut in Calgary.

The winner of this matchup will take on the winner of Team Lawes vs. Team Reese-Hansen in the Elite 8.

Team Rachel Homan, the reigning Canadian and world champions, are coming off a season for the ages in 2023-24.

They finished with an incredible record of 67-7, winning seven of 10 events, including the Scotties Tournament of Hearts and World Women’s Curling Championship in Sydney, N.S.

Team Homan also captured the PointsBet Invitational in Oakville by beating Team Kerri Einarson in the final, 9-7.

The Ottawa crew will look to defend their title, starting with a matchup against Edmonton’s Team Gabby Wood, the Canadian Collegiate Athletic Association champions from a season ago, in the Sweep 16.

[🅻🅸🆅🅴 CLICK HERE TO WATCH LIVE ONLINE](https://special.procast.live/?refd_by=clicktvt)

[🆆🅰🆃🅲🅷 CLICK HERE TO LIVE STREAM](https://special.procast.live/?refd_by=clicktvt)

Sudden-death drama will be the storyline over five days of high-calibre curling when the 2024 PointsBet InvitationalOpens in a new window gets underway Wednesday at the WinSport Event Centre in Calgary. Sixteen men’s and sixteen women’s teams are entered in the third annual PointsBet Invitational, all looking to get their 2024-25 campaigns kicked off in style, not to mention grab a big chunk of a prize purse in excess of $350,000.

[🅻🅸🆅🅴 CLICK HERE TO WATCH LIVE ONLINE](https://special.procast.live/?refd_by=clicktvt)

[🆆🅰🆃🅲🅷 CLICK HERE TO LIVE STREAM](https://special.procast.live/?refd_by=clicktvt)

Winnipeg’s Team Kaitlyn Lawes are set to begin their third season as a foursome and will take on Victoria’s Taylor Reese-Hansen in the opening round of the Sweep 16.

Team Lawes have lost in the semifinals in each of the previous two PointsBet Invitational events while Team Reese-Hansen will make their debut after winning the U25 NextGen Classic earlier this season.

As a Scotties Tournament of Hearts rookie, 25-year-old Selena Sturmay led her young Alberta foursome to a playoff appearance in front of a hometown crowd at Calgary’s WinSport arena last February.

Sturmay and company return to the location of their memorable run last winter, looking for some more magic at the PointsBet Invitational.

They’ll take on Saskatoon’s Team Ashley Thevenot, who also competed at the Calgary Scotties, in the Sweep 16.

Team Thevenot were skipped by Skylar Ackerman at last year's Scotties and almost made the playoffs with a 4-4 round robin record. Ackerman announced at the end of the season she was leaving competitive curling. Thevenot, who was the vice, took over skip duties for 2024-25 and added Brittany Tran to the team.

As a 13th seed, Sturmay upset a rink led by Chelsea Carey at the inaugural Sweep 16 in 2022 before losing to Jennifer Jones in the Elite 8.

Thevenot will make her PointsBet Invitational debut in Calgary.

The winner of this matchup will take on the winner of Team Lawes vs. Team Reese-Hansen in the Elite 8.

Team Rachel Homan, the reigning Canadian and world champions, are coming off a season for the ages in 2023-24.

They finished with an incredible record of 67-7, winning seven of 10 events, including the Scotties Tournament of Hearts and World Women’s Curling Championship in Sydney, N.S.

Team Homan also captured the PointsBet Invitational in Oakville by beating Team Kerri Einarson in the final, 9-7.

The Ottawa crew will look to defend their title, starting with a matchup against Edmonton’s Team Gabby Wood, the Canadian Collegiate Athletic Association champions from a season ago, in the Sweep 16.

[🅻🅸🆅🅴 CLICK HERE TO WATCH LIVE ONLINE](https://special.procast.live/?refd_by=clicktvt)

[🆆🅰🆃🅲🅷 CLICK HERE TO LIVE STREAM](https://special.procast.live/?refd_by=clicktvt)

**Comment by kristinsulap** [comment]
PointsBet Invitational 2024

**Comment by itonirban** [comment]
PointsBet Invitational 2024
