### ISSUE TITLE
GPTQ Import Error 

### ISSUE THREAD

**Issue by chintan-ushur** [vllm-project/llm-compressor#696]
**Describe the bug**
While importing GTPQModifier, below error is appears:

```
from llmcompressor.modifiers.quantization import GPTQModifier

ImportError: cannot import name 'ActivationOrdering' from 'compressed_tensors.quantization
```

**Expected behavior**
Successful import

**Environment**
Include all relevant environment information:
1. OS - Ubuntu 20.04]
2. Python version - 3.10.12
3. LLM Compressor version - 0.2.0
4. ML framework version(s) [e.g. torch 2.3.1]: torch 2.4.1
5. Other relevant environment information [e.g. hardware, CUDA version]: A100, CUDA 12.1

**Comment by mgoin** [comment]
What version is your compressed-tensors? Could you try `pip install -U compressed-tensors`?

**Comment by chintan-ushur** [comment]
Thanks @mgoin , existing version 

`compressed-tensors==0.5.0
`

Upgraded it to 0.6.0; issue is addressed, thank you for quick reply.
