### ISSUE TITLE
Saving an existing 2:4 model as compressed doesn't produce a usable "quant_config"

### ISSUE THREAD

**Issue by mgoin** [vllm-project/llm-compressor#72]
We have an existing model [neuralmagic/SparseLLama-2-7b-ultrachat_200k-pruned_50.2of4](https://huggingface.co/neuralmagic/SparseLLama-2-7b-ultrachat_200k-pruned_50.2of4) that has already been pruned to 2:4 sparsity at BF16, but it is just stored as a dense HF checkpoint. 
I want to make a compressed 2:4 version of this model with the associated config so I can load it directly into a 2:4 sparse vLLM backend.

Here is the code I tried for saving as compressed:
```python
from llmcompressor.transformers import SparseAutoModelForCausalLM

model = SparseAutoModelForCausalLM.from_pretrained("neuralmagic/SparseLLama-2-7b-ultrachat_200k-pruned_50.2of4", torch_dtype="auto")
model.save_pretrained("output", save_compressed=True)
```

I pushed the produced model here: https://huggingface.co/mgoin/SparseLLama-2-7b-ultrachat_200k-pruned_50.2of4-compressed-tensors

The model is saved as compressed, but the [config](https://huggingface.co/mgoin/SparseLLama-2-7b-ultrachat_200k-pruned_50.2of4-compressed-tensors/blob/main/config.json) is lacking sufficient detail to be considered a compressed-tensors model by vLLM:
```json
  "compression_config": {
    "sparsity_config": {
      "format": "sparse-bitmask",
      "global_sparsity": 0.4805290754567787,
      "registry_requires_subclass": false,
      "sparsity_structure": "2:4"
    }
  },
```

## Proposal

If I understand the structure of other quantized models, I think producing a config something like this would be more reasonable for use with vLLM (based off this [config](https://huggingface.co/nm-testing/llama7b-one-shot-2_4-w4a16-marlin24-t/blob/main/config.json)):
```json
  "compression_config": {
    "config_groups": {
      "group_0": {
        "input_activations": null,
        "output_activations": null,
        "weights": null,
        "targets": [
          "Linear"
        ],
      }
    },
    "format": "24", # not sure
    "global_compression_ratio": 1.896287597650382,
    "ignore": [
      "lm_head" # not sure
    ],
    "quant_method": "compressed-tensors",
    "quantization_status": "frozen",
    "sparsity_config": {
      "format": "sparse-bitmask",
      "global_sparsity": 0.4805290754567787,
      "registry_requires_subclass": false,
      "sparsity_structure": "2:4"
    }
  },
```

**Comment by Satrat** [comment]
@mgoin just to clarify, you're running 2:4 sparseGPT and not quantizing the model? The only sparsity compression we currently have is the `sparse-bitmask`, so this would be the expected result. I think this issue is more on the vLLM side, where we don't currently recognize any sparsity only compression formats

**Comment by markurtz** [comment]
Closing this issue out as we have #148 open which will be fixed by the latest push to get 2:4 sparsity support with quantization fully working.
