### ISSUE TITLE
[ＤＩＲＥＴＴＡ＠ＴＶ]Ｌｉｖｅｒｐｏｏｌ－Ｂｏｌｏｇｎａ Ｉｎ Ｄｉｒｅｔｔａ Ｓｔｒｅａｍｉｎｇ Ｇｒａｔｉｓ ０２ Ｏｔｔｏｂｒｅ

### ISSUE THREAD

**Issue by khang569** [vllm-project/llm-compressor#763]
Lipsia-Juve diretta Champions League: segui la partita di oggi LIVE. I bianconeri tornano in campo per la seconda sfida della loro campagna europea. Segui tutti gli aggiornamenti in tempo reale

LIPSIA - La Juventus sfida in Champions League il Lipsia di Marco Rose dopo la convincente vittoria per 3-1 sul Psv. I tedeschi hanno perso la sfida d'esordio in casa dell'Atletico Madrid e oggi proveranno a rifarsi davanti ai propri tifosi. Segui la partita in diretta

Giuntoli: "Siamo all'inizio di un progetto, oggi un bel banco di prova"
Intervistato a bordocampo da Prime, il dirigente bianconero ha commentato così la partita: "Ci sono tanti ragazzi nuovi, c'è tanta curiosità. Parlare dei singoli è scorretto ci sono tanti calciatori bravi. Siamo curiosi di capire quello che possiamo fare, siamo all'inizio di un progetto lungo. Loro hanno tanti bravi calciatori, è una squadra importante che sta facendo bene da tempo. Sarà un bel banco di prova".

Thiago Motta: "Vlahovic deve accettare le critiche, sono normali"
Nel pre-partita l'allenatore della Juventus ha parlato così ai microfoni di Prime: "Tutti possono partecipare perché abbiamo tanti giocatori forti. Le scelte dipendono dal momento e dagli avversari. È un peccato farli giocare tutti ma non posso. Vlahovic deve accettare le critiche, sono normali per un attaccante quando non segna. Io da allenatore sono contento perché per me è importante che sia in sintonia con il gruppo".

Lipsia-Juve: il fischio d'inizio alle 21, dove vederla
La partita di Champions League dei bianconeri inizierà alle 21 in contemporanea con le altre sei sfide in programma, inclusa quella tra Liverpool e Bologna. SCOPRI COME VEDERLA IN DIRETTA

Juve: i precedenti contro le tedesche
La Juventus ha vinto le ultime quattro sfide contro squadre tedesche mantenendo sempre la porta inviolata. Due stagioni fa i bianconeri hanno fermato il Friburgo in Europa League, vincendo 1-0 a Torino e 0-2 in Germania, mentre nel 2019 hanno rifilato un 3-0 al Leverkusen all'Allianz Stadium e un 2-0 alla BayArena.

La formazione ufficiale del Lipsia
LIPSIA (4-4-2): Gulacsi; Geertruida, Orban, Lukeba, Raum; Baumgartner, Seiwald, Haidara, Simons; Sesko, Openda. All. Rose

Juve: le scelte ufficiali Thiago Motta
JUVENTUS (4-2-3-1): Di Gregorio; Savona, Kalulu, Bremer, Cambiaso; Fagioli, McKennie; Gonzalez, Koopmeiners, Yildiz; Vlahovic. All. Thiago Motta

**Comment by aryangex** [comment]
sdfee
