### ISSUE TITLE
When to support multi-nodes quantization?

### ISSUE THREAD

**Issue by IEI-mjx** [vllm-project/llm-compressor#831]
For large models (Parameter > 350B)，weight can't be loaded with single node (ex: 80GB X 8).
Although methods like cpu/disk offloading  can overcome the limits of GPU memory, but the quantization speed is quite slow due to the weight loading process from cpu or disk.
I think if we can quantize large models with multi-nodes may solve this problem?

**Comment by IEI-mjx** [comment]
thanks,
Looking forward to the release of your new version！

**Comment by robertgshaw2-neuralmagic** [comment]
Check out the accelerate integration for large models. Please feel free to open an issue. Thanks!
