### ISSUE TITLE
How to quantize a model not in  AutoModelForCausalLM list?

### ISSUE THREAD

**Issue by IEI-mjx** [vllm-project/llm-compressor#851]
We are trying to quantize our own pretrained model which haven't been added to transformers model list.
As far as I know, I just have to change the model loading process like substituting all the AutoModelForCausalLM to xxForCausalLM in llmcompressor, especially path like 'llmcompressor/transformers'.
However, the compression process 'looked' normal, but our model size (76GB) was not changed.

**Comment by robertgshaw2-neuralmagic** [comment]
Can you share the code you used?

We are working on improving our integration with `transformers` to avoid the need for `SparseAutoModelForCausalLM` - which currently implements some utilities associated with saving and loading models in compressed format. 

So to use a regular transformers model for now, we need to use some of these saving utilities directly.

**Comment by robertgshaw2-neuralmagic** [comment]
see https://github.com/vllm-project/llm-compressor/pull/832 for the ongoing work on this

**Comment by IEI-mjx** [comment]
Thank you for your reply.
We are currently using llmcompressor version-0.2.0. 
I will take a look at this PR #832

**Comment by kylesayrs** [comment]
Hi @IEI-mjx 

You you'll need to use the `wrap_hf_model_class` to wrap the model class which you'd like to use. Note that this API may change in the future.

Example:
```python3
from transformers import MllamaForConditionalGeneration

from llmcompressor.modifiers.quantization import QuantizationModifier
from llmcompressor.transformers import oneshot, wrap_hf_model_class

MODEL_ID = "meta-llama/Llama-3.2-11B-Vision-Instruct"

model_class = wrap_hf_model_class(MllamaForConditionalGeneration)
model = model_class.from_pretrained(MODEL_ID, device_map="auto", torch_dtype="auto")
```

If you're still have issues, let me know the model and class you're using and I'd be happy to take a deeper look

**Comment by IEI-mjx** [comment]
> Hi @IEI-mjx
> 
> You you'll need to use the `wrap_hf_model_class` to wrap the model class which you'd like to use. Note that this API may change in the future.
> 
> Example:
> 
> ```python
> from transformers import MllamaForConditionalGeneration
> 
> from llmcompressor.modifiers.quantization import QuantizationModifier
> from llmcompressor.transformers import oneshot, wrap_hf_model_class
> 
> MODEL_ID = "meta-llama/Llama-3.2-11B-Vision-Instruct"
> 
> model_class = wrap_hf_model_class(MllamaForConditionalGeneration)
> model = model_class.from_pretrained(MODEL_ID, device_map="auto", torch_dtype="auto")
> ```
> 
> If you're still have issues, let me know the model and class you're using and I'd be happy to take a deeper look

Thank you so much! I resolved the issue. In my state dict file, the weight matrices in the MoE and attention layers were concatenated, which made direct compression impossible. By chunking these weight matrices, the problem was resolved.

By the way, if I want to compress my original model, where the weight shape in the MoE layer is [num_experts, 2 * ffn_hidden_size, hidden_size], which part of the LLMCompressor backend should I modify?
