### ISSUE TITLE
vllm not support W8A8_Int8 deepseek_v2

### ISSUE THREAD

**Issue by jli943** [vllm-project/llm-compressor#859]
**Describe the bug**
vllm not support W8A8_Int8 deepseek_v2

**Environment**
Include all relevant environment information:
2. torch                             2.4.0
3. Python 3.10.13
4. llmcompressor                     0.2.0
6. vllm                              0.6.3.post1
7. cuda_12.1.r12.1/compiler.32688072_0
8.  NVIDIA A100

**Code**
examples/quantizing_moe/deepseek_moe_w8a8_int8.py

**Errors**
[rank0]: Traceback (most recent call last):
[rank0]:   File "/ossfs/node_48714514/workspace/vllm_lc.py", line 21, in <module>
[rank0]:     llm = LLM(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 177, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 573, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 334, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 47, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 40, in _init_executor
[rank0]:     self.driver_worker.load_model()
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/worker/worker.py", line 183, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1058, in load_model
[rank0]:     self.model = get_model(model_config=self.model_config,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
[rank0]:     return loader.load_model(model_config=model_config,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 398, in load_model
[rank0]:     model = _initialize_model(model_config, self.load_config,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 175, in _initialize_model
[rank0]:     return build_model(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 160, in build_model
[rank0]:     return model_class(config=hf_config,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/deepseek_v2.py", line 490, in __init__
[rank0]:     self.model = DeepseekV2Model(config,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/deepseek_v2.py", line 429, in __init__
[rank0]:     self.start_layer, self.end_layer, self.layers = make_layers(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 419, in make_layers
[rank0]:     [PPMissingLayer() for _ in range(start_layer)] + [
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 420, in <listcomp>
[rank0]:     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/deepseek_v2.py", line 431, in <lambda>
[rank0]:     lambda prefix: DeepseekV2DecoderLayer(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/deepseek_v2.py", line 359, in __init__
[rank0]:     self.mlp = DeepseekV2MoE(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/models/deepseek_v2.py", line 114, in __init__
[rank0]:     self.experts = FusedMoE(num_experts=config.n_routed_experts,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 212, in __init__
[rank0]:     self.quant_method = quant_config.get_quant_method(self, prefix)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py", line 79, in get_quant_method
[rank0]:     return CompressedTensorsMoEMethod.get_moe_method(self)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors_moe.py", line 48, in get_moe_method
[rank0]:     raise RuntimeError(
[rank0]: RuntimeError: Unsupported FusedMoe scheme: num_bits=8 type='int' symmetric=True group_size=None strategy='channel' block_structure=None dynamic=False actorder=None observer='minmax' observer_kwargs={}, num_bits=8 type='int' symmetric=True group_size=None strategy='token' block_structure=None dynamic=True actorder=None observer='memoryless' observer_kwargs={}

**Comment by dsikka** [comment]
Hi @jli943 - yes, vllm currently only supports W4A16, W8A16, W8W8_fp8 for Fused MoE compressed-tensors models. There is currently no kernel support for W8W8_int8.

**Comment by twoapples1** [comment]
have any plan on it ?
