### ISSUE TITLE
Add support to trust_remote_code

### ISSUE THREAD

**Issue by anmarques** [vllm-project/llm-compressor#89]
**Is your feature request related to a problem? Please describe.**
I had an issue using oneshot() for a model that required trust_remote_code since the instantiation of the tokenizer also requires this argument. I was able to circumvent by passing the tokenizer to oneshot(), but this still is a needed feature.

**Describe the solution you'd like**
Add trust_remote_code as a valid argument and use it when instantiating the model and the tokenizer.

**Comment by kylesayrs** [comment]
Which tokenizer was this?
