### ISSUE TITLE
ImportError: cannot import name 'freeze_module_quantization' from 'compressed_tensors.quantization

### ISSUE THREAD

**Issue by liangjason87** [vllm-project/llm-compressor#910]
**Describe the bug**
Following this example of fp8 quantization https://github.com/vllm-project/llm-compressor/tree/main/examples/quantization_w8a8_fp8 , getting an import error with one of the modules from compressed-tensors. Tried installing from source/upgrading the module itself, but still hitting this error.

**Expected behavior**
FP8 quant weights are created.

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 20.04]:  Ubuntu 20.04.6 LTS"
2. Python version [e.g. 3.7]: Python 3.12.7
3. LLM Compressor version or commit hash [e.g. 0.1.0, `f7245c8`]: latest
4. ML framework version(s) [e.g. torch 2.3.1]:
5. Other Python package versions [e.g. vLLM, compressed-tensors, numpy, ONNX]: latest
6. Other relevant environment information [e.g. hardware, CUDA version]: 

**To Reproduce**
Follow example code and attempt to run script with weights.

**Errors**

Traceback (most recent call last):
  File "/media/nvme1n1/vllm_quant.py", line 3, in <module>
    from llmcompressor.modifiers.quantization import QuantizationModifier
  File "/home/azureuser/.conda/envs/vllm_quant/lib/python3.12/site-packages/llmcompressor/modifiers/quantization/__init__.py", line 3, in <module>
    from .gptq import *
  File "/home/azureuser/.conda/envs/vllm_quant/lib/python3.12/site-packages/llmcompressor/modifiers/quantization/gptq/__init__.py", line 3, in <module>
    from .base import *
  File "/home/azureuser/.conda/envs/vllm_quant/lib/python3.12/site-packages/llmcompressor/modifiers/quantization/gptq/base.py", line 4, in <module>
    from compressed_tensors.quantization import (
ImportError: cannot import name 'freeze_module_quantization' from 'compressed_tensors.quantization' (/media/nvme1n1/compressed-tensors/src/compressed_tensors/quantization/__init__.py)

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by dsikka** [comment]
Hi @liangjason87 we recently went through a bit of a restructure in compressed-tensors and llm-compressor.
Can you confirm you're using latest llm-compressor? The change was made as of: Commit 18e9a9f
Thanks

**Comment by ymkymkymkymx** [comment]
`pip install compressed-tensors==0.7.1`   solved my problem. `pip install llmcompressor` auto installed compressed-tensors==0.8.0 which caused this error.

**Comment by dsikka** [comment]
Can you confirm what llmcompressor version you’re using?

**Comment by ymkymkymkymx** [comment]
> Can you confirm what llmcompressor version you’re using?

pip install llmcompressor==0.1.0 , I guess the package management list should specify the compressed-tensors version?

**Comment by dsikka** [comment]
We generally don’t hardcode the compressed tensors version. I could also strongly suggest updating your llmcompressor to 0.2.0

**Comment by ymkymkymkymx** [comment]
> We generally don’t hardcode the compressed tensors version. I would also strongly suggest updating your llmcompressor to 0.2.0

I tried 0.2.0 and also met this problem, but I didn't check if the fix work.

**Comment by liangjason87** [comment]
Sorry did not monitor this as well, this solved my issue, thanks!
