### ISSUE TITLE
Does any one use your own custom quantization with `llm-compressor`?

### ISSUE THREAD

**Issue by foreverlms** [vllm-project/llm-compressor#915]
I want to know if we coud customize our own quantization method. For the docs, the quantization methods are not very wide. Should I have to modify the `compress tensors` to support customized quantization?

**Comment by kylesayrs** [comment]
Hi @foreverlms! Could you provide some more details as to what you're looking to implement?

You can find an example implementations of compress modifiers in the `src/llmcompressor/modifiers` folders, for example (src/llmcompressor/modifiers/smoothquant/base.py)[https://github.com/vllm-project/llm-compressor/blob/main/src/llmcompressor/modifiers/smoothquant/base.py]

**Comment by foreverlms** [comment]
> Hi @foreverlms! Could you provide some more details as to what you're looking to implement?
> 
> You can find an example implementations of compress modifiers in the `src/llmcompressor/modifiers` folders, for example (src/llmcompressor/modifiers/smoothquant/base.py)[https://github.com/vllm-project/llm-compressor/blob/main/src/llmcompressor/modifiers/smoothquant/base.py]

Yes, I know these and I propose to do so. But I found finally this quantization scripts will call [compressed-tensors](https://github.com/neuralmagic/compressed-tensors) to carry out the quantization. So I was wondering If I should co-check the [compressed-tensors](https://github.com/neuralmagic/compressed-tensors)`

**Comment by foreverlms** [comment]
I know what you mean, I will close this.
