### ISSUE TITLE
Batch size > 1?

### ISSUE THREAD

**Issue by fzyzcjy** [vllm-project/llm-compressor#933]
Hi thanks for the library! I wonder whether it is possible to run with batch size > 1 when doing calibration, since usually larger batch size can make running faster.

(I am following the https://github.com/vllm-project/llm-compressor/tree/main/examples/quantization_kv_cache demo)

**Comment by kylesayrs** [comment]
Hi @fzyzcjy! We are working on supporting this (and more customized calibration pipelines) over the course of the next month or so.

While some modifiers do not easily support custom batch sizes (but will in the future), the `QuantizationModifier` should be capable of this with just a few changes.

I've provided some starter code below, feel free to use it and test this out yourself.

Best!
-Kyle

[llmcompressor/modifiers/quantization/quantization/base.py](https://github.com/vllm-project/llm-compressor/blob/a47137d834a2be8f8fcd49458f121b08ba34e2c9/src/llmcompressor/modifiers/quantization/quantization/base.py#L317-L335)
```python3
def _calibrate(self, module: Module):
    class_name = self.__class__.__name__.replace("PyTorch", "")
    logger.info(
        f"Running {class_name} calibration with "
        f"{len(self.calibration_dataloader_)} samples..."
    )

    module_training = module.training
    module.eval()

    dataloader = create_batch_dataloader(self.calibration_dataloader_.dataset, batch_size=BATCH_SIZE)
    run_calibration_forward(
        module,
        #self.calibration_dataloader_,
        dataloader,
        self.num_calibration_steps,
        self.calibration_function_,
    )

    if module_training:
        module.train()
```

[llmcompressor/transformers/finetune/data/data_helpers.py](https://github.com/vllm-project/llm-compressor/blob/a47137d834a2be8f8fcd49458f121b08ba34e2c9/src/llmcompressor/transformers/finetune/data/data_helpers.py)
```python3
def create_batch_dataloader(
    dataloader: torch.utils.data.DataLoader,
    batch_size: int,
) -> torch.utils.data.DataLoader:
    """
    Create a dataloader whose batch size is equal to the size of the dataset
    :param dataset: dataset used to generate dataloader
    :param batch_size: batch size of new dataloader
    :return: dataloader
    """
    dataset = dataloader.dataset
    sampler = dataloader.sampler.__class__(dataset)

    def pad_sequences(batch):
        # extract input_ids and attention_mask from the batch
        input_ids = [torch.tensor(item["input_ids"]).squeeze(0) for item in batch]
        masks = [torch.tensor(item["attention_mask"]).squeeze(0) for item in batch]

        # while 0 is not necessarily the "correct" padding value, the padded
        # input_ids are ignored according to the attention_mask
        pad_input_ids = pad_sequence(input_ids, batch_first=True, padding_value=0)
        pad_masks = pad_sequence(masks, batch_first=True, padding_value=0)

        return {
            "input_ids": pad_input_ids,
            "attention_mask": pad_masks,
        }

    return torch.utils.data.DataLoader(
        dataset,
        batch_size=batch_size,
        sampler=sampler,
        collate_fn=pad_sequences,
        pin_memory=True,
    )
```

**Comment by fzyzcjy** [comment]
Thank you for the explanation and code! As I am a new learner in this subfield, I will firstly stick to the released version instead of hacking it immediately now, and looking forward to later release :)
