### ISSUE TITLE
Does `one_shot` save model twice?

### ISSUE THREAD

**Issue by fzyzcjy** [vllm-project/llm-compressor#936]
Hi thanks for the lib! When checking https://github.com/vllm-project/llm-compressor/issues/935, it seems that `one_shot` auto saves everything to the output folder. That looks great, but if I understand correctly, https://github.com/vllm-project/llm-compressor/blob/a47137d834a2be8f8fcd49458f121b08ba34e2c9/examples/quantization_kv_cache/llama3_fp8_kv_example.py#L99 here we want to manually save. Thus it seems the example script saves everything twice.

**Comment by kota-iizuka** [comment]
I have confirmed that the same problem occurs. Probably due to https://github.com/vllm-project/llm-compressor/blob/a47137d834a2be8f8fcd49458f121b08ba34e2c9/src/llmcompressor/transformers/finetune/training_args.py#L61, if you specify `output_dir` as shown below, it will be saved once.

```diff
- oneshot(model=model, recipe=recipe)
- model.save_pretrained(SAVE_DIR)
+ oneshot(model=model, recipe=recipe, output_dir=SAVE_DIR)
  tokenizer.save_pretrained(SAVE_DIR)
```

**Comment by fzyzcjy** [comment]
> it will be saved once

Well it seems the save operation is done twice, but write (and overwrite) to the save folder...

**Comment by kota-iizuka** [comment]
Did you delete `model.save_pretrained(SAVE_DIR)` ?

**Comment by fzyzcjy** [comment]
@kota-iizuka I personally want to have model.save_pretrained (and tokenizer.save_pretrained) for better fine-control indeed

**Comment by fzyzcjy** [comment]
Thanks!
