### ISSUE TITLE
Does not generate output for `--quantization-param-path`

### ISSUE THREAD

**Issue by fzyzcjy** [vllm-project/llm-compressor#937]
Hi thanks for the library! I am following https://github.com/vllm-project/llm-compressor/tree/main/examples/quantization_kv_cache to create a quantized model and the performance is quite bad. When looking at doc,

https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html says:

> --quantization-param-path
Path to the JSON file containing the KV cache scaling factors. ***This should generally be supplied, when KV cache dtype is FP8.*** Otherwise, KV cache scaling factors default to 1.0, which may cause accuracy issues. FP8_E5M2 (without scaling) is only supported on cuda version greater than 11.8. On ROCm (AMD GPU), FP8_E4M3 is instead supported for common inference criteria.

So I guess we should provide this file. However, it seems the quantization_kv_cache example does not output such a file. Thus I wonder whether to get it?

**Comment by robertgshaw2-neuralmagic** [comment]
- Hey @fzyzcjy, `--quantization-param-path` in vLLM is a legacy pathway. The example you reference is the right one for making quantized KV cache with VLLM
- When you say the performance is bad --- is this accuracy or speed?

**Comment by robertgshaw2-neuralmagic** [comment]
Im going to close this for now. Please reopen if you have further questions about KV cache quantization.

**Comment by fzyzcjy** [comment]
Hi thanks for the reply.

> When you say the performance is bad --- is this accuracy or speed?

Bad accuracy. But weirdly, one model gets very bad accuracy, while another model is pretty good and has no degrade at all!

**Comment by robertgshaw2-neuralmagic** [comment]
> Hi thanks for the reply.
> 
> > When you say the performance is bad --- is this accuracy or speed?
> 
> Bad accuracy. But weirdly, one model gets very bad accuracy, while another model is pretty good and has no degrade at all!

Hm - can you share anything more?

We know that KV cache compression is not lossless --- which is why we do not really recommend it other than for research so far. We are currently working on integrating some new "transform-based" methods that help with the accuracy of KV cache / attention compression:
- https://arxiv.org/pdf/2404.00456
- https://arxiv.org/abs/2405.16406

**Comment by fzyzcjy** [comment]
@robertgshaw2-neuralmagic Sure! 

* Qwen2.5-Math-7B-Instruct on math questions: When using fp8 kv cache, accuracy of my internal math benchmark drop from 41.4% to 14.9%
* Llama3.1-8B-Instruct on the same benchmark: No accuracy drop at all
