### ISSUE TITLE
Understanding fp8 static vs dynamic

### ISSUE THREAD

**Issue by 0xymoro** [vllm-project/llm-compressor#940]
Looking over here:

https://medium.com/squeezebits-team-blog/vllm-vs-tensorrt-llm-7-weight-activation-quantization-331cf9eadc0d

I'm seeing really negligible performance hit on dynamic vs static fp8, while static takes calibration and results in worse performance generally on downstream tasks. Is there any argument for static or is it just something of the past? What am I missing?

**Comment by molereddy** [comment]
Static quantization is faster since you avoid calibration at inference time

**Comment by robertgshaw2-neuralmagic** [comment]
There is a <1% end-to-end performance impact for static vs dynamic. We suggest using dynamic since accuracy will be better and more robust to outliers.
