### ISSUE TITLE
pip install llmcompressor returns with errors

### ISSUE THREAD

**Issue by teman67** [vllm-project/llm-compressor#95]
**Describe the bug**

pip install llmcompressor returns with errors:

"""
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python <3.12,>=3.8.0
ERROR: Could not find a version that satisfies the requirement llmcompressor (from versions: none)
ERROR: No matching distribution found for llmcompressor
"""

**Environment**
Include all relevant environment information:
1. VSCode
2. Python version == 3.12.3

**Comment by robertgshaw2-neuralmagic** [comment]
We currently do not distribute a Python 3.12 build. You can install from source or downgrade Python to 3.11

`pip install -e .`

**Comment by mgoin** [comment]
I think we can add a Python 3.12 build in the next release, thanks for raising.
