### ISSUE TITLE
w8a8_fp8 quantization

### ISSUE THREAD

**Issue by hochen1** [vllm-project/llm-compressor#958]
I quantized opt-125M to fp8, according to  [llama3_example.py](https://github.com/vllm-project/llm-compressor/blob/main/examples/quantization_w8a8_fp8/llama3_example.py), but I find that model saved as fp16, although it has scalar, like this:

![image](https://github.com/user-attachments/assets/2d7ce8e6-c669-4c68-aebe-b016187d87aa)

I am wondering if this is an expected behavior.

**Comment by dsikka** [comment]
Weight scales are stored as either fp16 or fp32

**Comment by dsikka** [comment]
Can you share the config file produce for the model, any modifications you made to the script and confirm the versions you used?

**Comment by hochen1** [comment]
I use llm-compressor==0.1.0.
config file:
`{
  "_name_or_path": "/workspace/Meta-Llama-3.1-8B-Instruct/",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 128000,
  "eos_token_id": [
    128001,
    128008,
    128009
  ],
  "head_dim": 128,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 14336,
  "max_position_embeddings": 131072,
  "mlp_bias": false,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 8,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": {
    "factor": 8.0,
    "high_freq_factor": 4.0,
    "low_freq_factor": 1.0,
    "original_max_position_embeddings": 8192,
    "rope_type": "llama3"
  },
  "rope_theta": 500000.0,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.46.3",
  "use_cache": true,
  "vocab_size": 128256
}`
conversion script:
`
from transformers import AutoModelForCausalLM, AutoTokenizer

from llmcompressor.modifiers.quantization import QuantizationModifier
from llmcompressor.transformers import oneshot

MODEL_ID = "/workspace/llm_workspace/opt-125m"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID, device_map="auto", torch_dtype="auto"
)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

recipe = QuantizationModifier(
    targets="Linear", scheme="FP8_DYNAMIC", ignore=["lm_head"]
)

oneshot(model=model, recipe=recipe)

print("========== SAMPLE GENERATION ==============")
input_ids = tokenizer("Hello my name is", return_tensors="pt").input_ids.to("cuda")
output = model.generate(input_ids, max_new_tokens=20)
print(tokenizer.decode(output[0]))
print("==========================================")

SAVE_DIR = "./" + "opt-125m" + "-FP8-Dynamic"
model.save_pretrained(SAVE_DIR)
tokenizer.save_pretrained(SAVE_DIR)
`

**Comment by hochen1** [comment]
I used llmcompressor=0.1.0, these are script and config file after conversion, and I also tried 0.3.0, the result is same:
```
{
  "_name_or_path": "/workspace/llm_workspace/opt-125m",
  "_remove_final_layer_norm": false,
  "activation_dropout": 0.0,
  "activation_function": "relu",
  "architectures": [
    "OPTForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 2,
  "do_layer_norm_before": true,
  "dropout": 0.1,
  "enable_bias": true,
  "eos_token_id": 2,
  "ffn_dim": 3072,
  "hidden_size": 768,
  "init_std": 0.02,
  "layer_norm_elementwise_affine": true,
  "layerdrop": 0.0,
  "max_position_embeddings": 2048,
  "model_type": "opt",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "prefix": "</s>",
  "torch_dtype": "float16",
  "transformers_version": "4.46.3",
  "use_cache": true,
  "vocab_size": 50272,
  "word_embed_proj_dim": 768
}

```
```
from transformers import AutoModelForCausalLM, AutoTokenizer

from llmcompressor.modifiers.quantization import QuantizationModifier
from llmcompressor.transformers import oneshot

MODEL_ID = "/workspace/llm_workspace/opt-125m"

# Load model.
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID, device_map="auto", torch_dtype="auto"
)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

# Configure the quantization algorithm and scheme.
# In this case, we:
#   * quantize the weights to fp8 with per channel via ptq
#   * quantize the activations to fp8 with dynamic per token
recipe = QuantizationModifier(
    targets="Linear", scheme="FP8_DYNAMIC", ignore=["lm_head"]
)

# Apply quantization.
oneshot(model=model, recipe=recipe)

# Confirm generations of the quantized model look sane.
print("========== SAMPLE GENERATION ==============")
input_ids = tokenizer("Hello my name is", return_tensors="pt").input_ids.to("cuda")
output = model.generate(input_ids, max_new_tokens=20)
print(tokenizer.decode(output[0]))
print("==========================================")

# Save to disk in compressed-tensors format.
SAVE_DIR = "./" + "opt-125m" + "-FP8-Dynamic"
model.save_pretrained(SAVE_DIR)
tokenizer.save_pretrained(SAVE_DIR)
```
I also want to know if the successful conversion result should be weight fp8, weight scale fp16 or fp32, and zero_point doesn't seem to be very useful?

**Comment by hochen1** [comment]
And, when I try the command according to the docs: 
```lm_eval   --model vllm   --model_args pretrained=$MODEL,add_bos_token=True   --tasks gsm8k  --num_fewshot 5 --batch_size auto --limit 250```
vllm can not initialize the w8a8 fp8 model architecture correctly
![image](https://github.com/user-attachments/assets/f97777d3-928b-45df-8dc4-713ce55486b5)

**Comment by robertgshaw2-neuralmagic** [comment]
Hey @hochen1 - we are in progress of updating our integration into `AutoModelForCausalLM` are pushed the updated examples to the main branch
- @horheynm - can you share instructions for installing from source that would work with the examples on main?
- @hochen1 - for now, you can unblock yourself by running the examples on `v0.3.0` (https://github.com/vllm-project/llm-compressor/tree/0.3.0/examples/quantization_w8a8_fp8). These use `SparseAutoModelForCausalLM` which handles the saving and loading properly

Sorry for the issue!

**Comment by robertgshaw2-neuralmagic** [comment]
Can you let me know if this resolves your issue?

**Comment by hochen1** [comment]
Problem solved! Thank you for your time.

**Comment by robertgshaw2-neuralmagic** [comment]
Thanks!
