### ISSUE TITLE
Can I load the `stage_quantization` model using `SparseAutoModelForCausalLM`?

### ISSUE THREAD

**Issue by jiangjiadi** [vllm-project/llm-compressor#962]
**Describe the bug**
I failed to load the model `neuralmagic/Sparse-Llama-3.1-8B-ultrachat_200k-2of4-quantized.w4a16` using `SparseAutoModelForCausalLM` and the Error is shown below:
![image](https://github.com/user-attachments/assets/5127ffb5-2bca-4de4-8fed-7c4a2ce982e1)

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 20.04]:
2. Python version [e.g. 3.7]: 3.10.13
3. LLM Compressor version or commit hash [e.g. 0.1.0, `f7245c8`]: latest code from repo
4. ML framework version(s) [e.g. torch 2.3.1]:
5. Other Python package versions [e.g. vLLM, compressed-tensors, numpy, ONNX]: compressed-tensors==0.8.0
6. Other relevant environment information [e.g. hardware, CUDA version]:

**To Reproduce**
Run the code below:
```
from transformers import AutoTokenizer
from llmcompressor.transformers import SparseAutoModelForCausalLM

model_path = 'neuralmagic/Sparse-Llama-3.1-8B-ultrachat_200k-2of4-quantized.w4a16'
compressed_model = SparseAutoModelForCausalLM.from_pretrained(
    model_path, torch_dtype="auto", device_map="cuda:0",
)
# tokenize the sample data
SAMPLE_INPUT = [
    "I love quantization because",
]
tokenizer = AutoTokenizer.from_pretrained(model_path)
inputs = tokenizer(SAMPLE_INPUT, return_tensors="pt", padding=True).to(
    compressed_model.device
)

# run the compressed model and decode the output
output = compressed_model.generate(**inputs, max_length=50)
print("========== SAMPLE GENERATION ==============")
text_output = tokenizer.batch_decode(output)
for sample in text_output:
    print(sample)
```

**Comment by dsikka** [comment]
Hi @jiangjiadi we do not support currently loading marlin24 compressed models in compressed-tensors. You can load this model using vllm
