### ISSUE TITLE
Pruned model not loading weights with transformers

### ISSUE THREAD

**Issue by hafezmg48** [vllm-project/llm-compressor#997]
**Describe the bug**
I followed the instructions on `examples/quantization_2of4_sparse_w4a16` and `examples/compressed_inference/fp8_compressed_inference.py` and modified it to perform a wanda pruning of Llama 3.1-8B-Instruct and then perform inference using AutoModelForCausalLM from transformers package. The pruning works fine and compresses and saves the model. But the inference does not load the model properly. First it takes a ton of time on the line `model.apply(model._initialize_weights)` from function `_load_pretrained_model` of `transformers/modeling_utils.py` and then prints out that some weights of model were not used when initializing LlamaForCausalLM: [listing all of the tensors of model]. Then at the inference `generate()` function raises exception `probability tensor contains either `inf`, `nan` or element < 0` which is expected as it didnt load the model weights properly.

**Expected behavior**
expected the model to load properly and run the inference.

**Environment**
Include all relevant environment information:

1. OS [e.g. Ubuntu 20.04]: Ubuntu 20.04.6 LTS
2. Python version: 3.11.8
3. LLM Compressor version: 0.3.0
4. ML framework version(s): torch 2.4.0
5. Other Python package versions: numpy 1.26.4, compressed-tensors 0.8.1, vllm 0.6.3.post1
6. Other relevant environment information: Tesla V100- 32G, Driver Version: 545.23.08 CUDA Version: 12.3

**To Reproduce**
The following codes are for compression and inference:

`model_compression.py`:
```python


from transformers import AutoTokenizer
from datasets import Dataset
from llmcompressor.transformers import SparseAutoModelForCausalLM, oneshot
from llmcompressor.modifiers.quantization import GPTQModifier
from llmcompressor.modifiers.pruning import WandaPruningModifier
import random
from datasets import load_dataset

model_id = "meta-llama/Meta-Llama-3.1-8B-Instruct"

num_samples = 512
max_seq_len = 1024 #8192

tokenizer = AutoTokenizer.from_pretrained(model_id)

preprocess_fn = lambda example: {"text": "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n{text}".format_map(example)}

dataset_name = "neuralmagic/LLM_compression_calibration"
dataset = load_dataset(dataset_name, split="train")
ds = dataset.shuffle().select(range(num_samples))
ds = ds.map(preprocess_fn)


recipe = WandaPruningModifier(sparsity=0.5,
                              # sequential_update=True
                            )


model = model_id

oneshot(
  model=model,
  dataset=ds,
  recipe=recipe,
  max_seq_length=max_seq_len,
  num_calibration_samples=num_samples,
  output_dir="~/models/meta-llama/Meta-Llama-3.1-70B-Instruct-pruned_0.5"
)


```

and `inference.py`  for inference:
```python
# run the inference
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers import LlamaForCausalLM

model_dir = "~/models/meta-llama/Meta-Llama-3.1-70B-Instruct-pruned_0.5"
tokenizer = AutoTokenizer.from_pretrained(model_dir)
compressed_model = LlamaForCausalLM.from_pretrained(
    model_dir,
    torch_dtype="auto",
    device_map="cuda",
)

input_text = "My name is"
input_ids = tokenizer(input_text, return_tensors="pt").input_ids.to("cuda")

output_ids = compressed_model.generate(input_ids, max_length=100)

output_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
print(output_text)
```

**Errors**
warning prints that some weights were not used for initialization, listing all the tensors:

> Some weights of the model checkpoint at ~/models/meta-llama/Meta-Llama-3.1-70B-Instruct-pruned_0.5 were not used when initializing LlamaForCausalLM: ['lm_head.weight.bitmask', 'lm_head.weight.compressed', 'lm_head.weight.row_offsets', 'lm_head.weight.shape', 'model.embed_tokens.weight.bitmask', 'model.embed_tokens.weight.compressed', 'model.embed_tokens.weight.row_offsets', 'model.embed_tokens.weight.shape', 'model.layers.0.input_layernorm.weight.bitmask', 'model.layers.0.input_layernorm.weight.compressed', 'model.layers.0.input_layernorm.weight.row_offsets', 'model.layers.0.input_layernorm.weight.shape', 'model.layers.0.mlp.down_proj.weight.bitmask', 'model.layers.0.mlp.down_proj.weight.compressed', 'model.layers.0.mlp.down_proj.weight.row_offsets', 'model.layers.0.mlp.down_proj.weight.shape', 'model.layers.0.mlp.gate_proj.weight.bitmask', 'model.layers.0.mlp.gate_proj.weight.compressed', 'model.layers.0.mlp.gate_proj.weight.row_offsets', 'model.layers.0.mlp.gate_proj.weight.shape', 'model.layers.0.mlp.up_proj.weight.bitmask', 'model.layers.0.mlp.up_proj.weight.compressed', 'model.layers.0.mlp.up_proj.weight.row_offsets', 'model.layers.0.mlp.up_proj.weight.shape', 'model.layers.0.post_attention_layernorm.weight.bitmask', 'model.layers.0.post_attention_layernorm.weight.compressed', 'model.layers.0.post_attention_layernorm.weight.row_offsets', 'model.layers.0.post_attention_layernorm.weight.shape', 'model.layers.0.self_attn.k_proj.weight.bitmask', 'model.layers.0.self_attn.k_proj.weight.compressed', 'model.layers.0.self_attn.k_proj.weight.row_offsets', 'model.layers.0.self_attn.k_proj.weight.shape', 'model.layers.0.self_attn.o_proj.weight.bitmask', 'model.layers.0.self_attn.o_proj.weight.compressed', 'model.layers.0.self_attn.o_proj.weight.row_offsets', 'model.layers.0.self_attn.o_proj.weight.shape', 'model.layers.0.self_attn.q_proj.weight.bitmask', 'model.layers.0.self_attn.q_proj.weight.compressed', 'model.layers.0.self_attn.q_proj.weight.row_offsets', 'model.layers.0.self_attn.q_proj.weight.shape', 'model.layers.0.self_attn.v_proj.weight.bitmask', 'model.layers.0.self_attn.v_proj.weight.compressed', 'model.layers.0.self_attn.v_proj.weight.row_offsets', 'model.layers.0.self_attn.v_proj.weight.shape', 'model.layers.1.input_layernorm.weight.bitmask', 'model.layers.1.input_layernorm.weight.compressed', 'model.layers.1.input_layernorm.weight.row_offsets',

the list continues... 
Then at generate() function gives exception Exception has occurred: 

> RuntimeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
> probability tensor contains either `inf`, `nan` or element < 0
>   File ".venv/lib/python3.11/site-packages/transformers/generation/utils.py", line 3297, in _sample
>     next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File ".venv/lib/python3.11/site-packages/transformers/generation/utils.py", line 2252, in generate
>     result = self._sample(
>              ^^^^^^^^^^^^^
>   File ".venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "run_inference.py", line 22, in <module>
>     output_ids = compressed_model.generate(input_ids, max_length=100)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/runpy.py", line 88, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.11/runpy.py", line 198, in _run_module_as_main (Current frame)
>     return _run_code(code, main_globals, None,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by dsikka** [comment]
Hi @hafezmg48  we do not support running compressed models in the marlin-24 format, as produced by that example script. You should be able to load the model using vllm however.

Example:
```python

from vllm import LLM, SamplingParams
sampling_params = SamplingParams(temperature=0.80, top_p=0.95)
llm = LLM(model=model_dir, dtype=torch.float16)
outputs = llm.generate(prompts, sampling_params)
```
